name: gpt_tokenizer
description: The implementation of BPE algorithm for sentence encode/decode
version: 0.1.0
repository: https://github.com/SimonWang9610/gpt_tokenizer/tree/main/packages/gpt_tokenizer

environment:
  sdk: ">=2.18.0 < 3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^7.2.9
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.72.1
  meta: ^1.8.0
